version: "3"
services:
  Squid:
    image: sameersbn/squid:3.5.27-2
    ports:
      - "3128:3128"
    volumes:
      - /srv/docker/squid/cache:/var/spool/squid
      - /disk/app/squid/squid.conf:/etc/squid/squid.conf
      - /disk/app/squid/htpasswd:/etc/squid/htpasswd
    restart: always
